### ISSUE TITLE
[ToDo] 05/21 View-細節修正

### ISSUE THREAD

**Issue by eudora-hsj** [codeboard-team/CodeBoard#78]
- [x] -[Card-show-出題] 無test_code時 Errror
- [x] -[已解題] result 移除

- [x] -[board/card] 身分按鈕顯示
- [x] -[解題中] 要補放 Ttes Code
- [x] -[題目敘述] 分行問題
